services:
  backend:
    image: matikant/backend-3r:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/sds-3r
      - JWT_SECRET=+AB44KcrVw8mTutUuI46CiBH/iCwg/RsvBHjH5jKLU4yVHbq8Q8+8qAIQySudDklPoJprX8ZosRuSbXJ3Tp44o6/H9D2mYJdkk3+8esAOtOH4T2/pslV/4zWVI1SLtrK66haCL1TUsazqUOvZFb6vE6gM2DlxPSbEE4lOQQsIi9ngC0qVuoQ985VmScNBuLnUCJCWYjJFg0MhRwT1yucvVaXeY0BKNNGAqa6Q==
      - JWT_EXPIRE=365d
      - JWT_COOKIE_EXPIRE=365
      - HOST=http://localhost
    depends_on:
      - mongo
    networks:
      - backend-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

volumes:
  mongo-data:


networks:
  backend-network:
    driver: bridge
